Repository Leets-Official/Carrot-BE, pull requests merged in 2024-11, with the labels that each got.

#22 Feature/#21 회원가입시 동정보 설정 추가
  src/main/java/land/leets/Carrot/domain/user/dto/request/CeoSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/entity/Ceo.java
  src/main/java/land/leets/Carrot/domain/user/entity/Employee.java
  src/main/java/land/leets/Carrot/domain/user/exception/ErrorMessage.java
  src/main/java/land/leets/Carrot/domain/user/exception/NicknameAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/repository/CeoRepository.java
  src/main/java/land/leets/Carrot/domain/user/repository/EmployeeRepository.java
  src/main/java/land/leets/Carrot/domain/user/service/CeoSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/EmployeeSignupService.java
Labels: feature, refactor

#24 Feature: 게시글 관련 CRUD API 구현
  src/main/java/land/leets/Carrot/domain/career/entity/WorkType.java
  src/main/java/land/leets/Carrot/domain/career/repository/WorkTypeRepository.java
  src/main/java/land/leets/Carrot/domain/career/service/WorkTypeService.java
  src/main/java/land/leets/Carrot/domain/location/entity/DetailArea.java
  src/main/java/land/leets/Carrot/domain/location/repository/LocationRepository.java
  src/main/java/land/leets/Carrot/domain/post/controller/PostController.java
  src/main/java/land/leets/Carrot/domain/post/controller/SuccessMessage.java
  src/main/java/land/leets/Carrot/domain/post/domain/PostData.java
  src/main/java/land/leets/Carrot/domain/post/domain/PostedPost.java
  src/main/java/land/leets/Carrot/domain/post/domain/ShortPostData.java
  src/main/java/land/leets/Carrot/domain/post/dto/request/GetPostedPostRequest.java
  src/main/java/land/leets/Carrot/domain/post/dto/request/PostDeleteRequest.java
  src/main/java/land/leets/Carrot/domain/post/dto/request/PostPostRequest.java
  src/main/java/land/leets/Carrot/domain/post/dto/response/PostResponse.java
  src/main/java/land/leets/Carrot/domain/post/dto/response/PostedPostResponse.java
  src/main/java/land/leets/Carrot/domain/post/dto/response/ShortPostResponse.java
  src/main/java/land/leets/Carrot/domain/post/dto/response/WorkTypeResponse.java
  src/main/java/land/leets/Carrot/domain/post/entity/Post.java
  src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
  src/main/java/land/leets/Carrot/domain/post/exception/ErrorMessage.java
  src/main/java/land/leets/Carrot/domain/post/mapper/PostDataMapper.java
  src/main/java/land/leets/Carrot/domain/post/mapper/PostSnapshotMapper.java
  src/main/java/land/leets/Carrot/domain/post/repository/PostRepository.java
  src/main/java/land/leets/Carrot/domain/post/repository/PostSnapshotRepository.java
  src/main/java/land/leets/Carrot/domain/post/service/PostService.java
  src/main/java/land/leets/Carrot/global/common/exception/BaseException.java
Labels: feature

#28 Feature: 지원, 채용 관련 API 구현
  src/main/java/land/leets/Carrot/domain/apply/controller/ApplyController.java
  src/main/java/land/leets/Carrot/domain/apply/controller/SuccessMessage.java
  src/main/java/land/leets/Carrot/domain/apply/domain/Applicant.java
  src/main/java/land/leets/Carrot/domain/apply/dto/request/ApplyRequest.java
  src/main/java/land/leets/Carrot/domain/apply/dto/response/GetApplicantResponse.java
  src/main/java/land/leets/Carrot/domain/apply/entity/Apply.java
  src/main/java/land/leets/Carrot/domain/apply/exception/ApplyErrorMessage.java
  src/main/java/land/leets/Carrot/domain/apply/exception/ApplyException.java
  src/main/java/land/leets/Carrot/domain/apply/repository/ApplyRepository.java
  src/main/java/land/leets/Carrot/domain/apply/service/ApplyService.java
  src/main/java/land/leets/Carrot/domain/post/entity/Post.java
  src/main/java/land/leets/Carrot/domain/user/entity/Employee.java
  src/main/java/land/leets/Carrot/domain/user/repository/EmployeeRepository.java
Labels: feature

#30 Refactor : post 조회, 마감 상태 변환 API
  src/main/java/land/leets/Carrot/domain/post/controller/PostController.java
  src/main/java/land/leets/Carrot/domain/post/dto/response/PostResponse.java
  src/main/java/land/leets/Carrot/domain/post/entity/Post.java
  src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
  src/main/java/land/leets/Carrot/domain/post/exception/PostErrorMessage.java
  src/main/java/land/leets/Carrot/domain/post/repository/PostRepository.java
  src/main/java/land/leets/Carrot/domain/post/service/PostService.java
  src/main/java/land/leets/Carrot/domain/user/entity/Ceo.java
Labels: refactor

#31 Feature : 마이페이지 api 개발
  src/main/java/land/leets/Carrot/domain/user/controller/ResponseMessage.java
  src/main/java/land/leets/Carrot/domain/user/controller/UserProfileController.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/BasicInfoUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/CeoSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeAdditionalInfoUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeCareerUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeSelfIntroUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeStrengthUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/CeoProfileResponse.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/EmployeeProfileResponse.java
  src/main/java/land/leets/Carrot/domain/user/entity/Ceo.java
  src/main/java/land/leets/Carrot/domain/user/entity/Employee.java
  src/main/java/land/leets/Carrot/domain/user/entity/User.java
  src/main/java/land/leets/Carrot/domain/user/exception/ErrorMessage.java
  src/main/java/land/leets/Carrot/domain/user/exception/InvalidUserTypeException.java
  src/main/java/land/leets/Carrot/domain/user/exception/UnknownUserTypeException.java
  src/main/java/land/leets/Carrot/domain/user/service/CeoSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/UserProfileService.java
  src/main/java/land/leets/Carrot/global/auth/annotation/CurrentUser.java
  src/main/java/land/leets/Carrot/global/auth/resolver/CurrentUserArgumentResolver.java
  src/main/java/land/leets/Carrot/global/config/WebConfig.java
Labels: feature

#38 Refactor/#35 이메일 인증 로직 변경
  src/main/java/land/leets/Carrot/domain/user/controller/ResponseMessage.java
  src/main/java/land/leets/Carrot/domain/user/controller/UserController.java
  src/main/java/land/leets/Carrot/domain/user/service/CeoSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/EmployeeSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/UserService.java
  src/main/java/land/leets/Carrot/global/config/SecurityConfig.java
Labels: feature, refactor

#42 Refactor : 경력 세부사항 설정
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeCareerUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/entity/Employee.java
  src/main/java/land/leets/Carrot/domain/user/entity/User.java
  src/main/java/land/leets/Carrot/domain/user/service/UserProfileService.java
  src/main/java/land/leets/Carrot/global/auth/jwt/dto/JwtFilter.java
Labels: feature, refactor

#46 Feature: 사업자 정보 조회 API 구현
  src/main/java/land/leets/Carrot/domain/user/controller/CeoErrorMessage.java
  src/main/java/land/leets/Carrot/domain/user/controller/SuccessMessage.java
  src/main/java/land/leets/Carrot/domain/user/controller/UserProfileController.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/GetCeoInfoResponse.java
  src/main/java/land/leets/Carrot/domain/user/exception/CeoException.java
  src/main/java/land/leets/Carrot/domain/user/repository/CeoRepository.java
  src/main/java/land/leets/Carrot/domain/user/service/CeoInfoService.java
Labels: feature

#49 Feat : 로그인 성공시 userid usertype 반환
  src/main/java/land/leets/Carrot/domain/user/controller/UserController.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/LoginResponse.java
  src/main/java/land/leets/Carrot/domain/user/service/LoginService.java
  src/main/java/land/leets/Carrot/global/auth/jwt/dto/JwtProvider.java
Labels: feature, refactor

#51 Fix: post image api
  src/main/java/land/leets/Carrot/domain/post/controller/PostController.java
  src/main/java/land/leets/Carrot/domain/post/dto/response/PostImageUrlResponse.java
  src/main/java/land/leets/Carrot/domain/post/service/PostService.java
Labels: fix

#55 Refactor : 커런트유저 관련 설정 변경 및 로직 수정
  src/main/java/land/leets/Carrot/domain/user/service/LoginService.java
  src/main/java/land/leets/Carrot/global/auth/jwt/dto/JwtFilter.java
  src/main/java/land/leets/Carrot/global/auth/jwt/dto/JwtProvider.java
  src/main/java/land/leets/Carrot/global/auth/resolver/CurrentUserArgumentResolver.java
Labels: refactor, fix

#57 Refactor : 반환 데이터 변경 및 세부 사항 수정
  src/main/java/land/leets/Carrot/domain/user/controller/UserProfileController.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/CeoSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/CeoBasicInfoResponse.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/CeoProfileResponse.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/EmployeeBasicInfoResponse.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/EmployeeProfileResponse.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/ProfileResponse.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/UserBasicInfoResponse.java
  src/main/java/land/leets/Carrot/domain/user/entity/Ceo.java
  src/main/java/land/leets/Carrot/domain/user/service/CeoSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/UserProfileService.java
Labels: feature, refactor

#59 Refactor : 응답 dto 형식 통일
  src/main/java/land/leets/Carrot/domain/user/controller/UserController.java
  src/main/java/land/leets/Carrot/domain/user/controller/UserProfileController.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/AdditionalInfoUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/BasicInfoUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/CareerUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeAdditionalInfoUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeCareerUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeSelfIntroUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeStrengthUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/LoginRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/SelfIntroUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/StrengthUpdateRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/LoginResponse.java
  src/main/java/land/leets/Carrot/domain/user/service/EmployeeSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/UserProfileService.java
Labels: refactor

#62 Fix: post 조회 예외처리 추가
  src/main/java/land/leets/Carrot/domain/post/repository/PostImageRepository.java
  src/main/java/land/leets/Carrot/domain/post/service/PostService.java
Labels: bug, fix
