Repository Leets-Official/Carrot-BE, pull requests merged in 2024-10, with the labels that each got.

#2 feature: 엔티티 생성
  build.gradle
  src/main/java/land/leets/Carrot/domain/apply/entity/Apply.java
  src/main/java/land/leets/Carrot/domain/business/entity/Business.java
  src/main/java/land/leets/Carrot/domain/career/entity/Career.java
  src/main/java/land/leets/Carrot/domain/career/entity/WorkType.java
  src/main/java/land/leets/Carrot/domain/interest/entity/Interest.java
  src/main/java/land/leets/Carrot/domain/location/entity/DetailArea.java
  src/main/java/land/leets/Carrot/domain/location/entity/DoArea.java
  src/main/java/land/leets/Carrot/domain/location/entity/Location.java
  src/main/java/land/leets/Carrot/domain/location/entity/SiArea.java
  src/main/java/land/leets/Carrot/domain/post/entity/Post.java
  src/main/java/land/leets/Carrot/domain/post/entity/PostSnapshot.java
  src/main/java/land/leets/Carrot/domain/post/entity/ShortWorkData.java
  src/main/java/land/leets/Carrot/domain/review/entity/Review.java
  src/main/java/land/leets/Carrot/domain/review/entity/enums/WorkType.java
  src/main/java/land/leets/Carrot/domain/strength/entity/Strength.java
  src/main/java/land/leets/Carrot/domain/strength/entity/StrengthMatch.java
  src/main/java/land/leets/Carrot/domain/user/entity/Gender.java
  src/main/java/land/leets/Carrot/domain/user/entity/User.java
Labels: enhancement

#4 Feature/#2 로그인 회원가입 기능구현
  src/main/java/land/leets/Carrot/global/auth/authentication/CustomAuthentication.java
  src/main/java/land/leets/Carrot/global/auth/dto/TokenResponse.java
  src/main/java/land/leets/Carrot/global/auth/dto/UserInfoResponse.java
  src/main/java/land/leets/Carrot/global/auth/exception/ErrorMessage.java
  src/main/java/land/leets/Carrot/global/common/domain/BaseTimeEntity.java
  src/main/java/land/leets/Carrot/global/common/exception/BaseException.java
  src/main/java/land/leets/Carrot/global/common/exception/GlobalExceptionHandler.java
  src/main/java/land/leets/Carrot/global/common/response/ResponseDto.java
  src/main/java/land/leets/Carrot/global/config/SecurityConfig.java
  src/main/java/land/leets/Carrot/global/config/SwaggerConfig.java
Labels: feature

#6 Feature/#3 jwt 토큰 인증
  src/main/java/land/leets/Carrot/global/auth/authentication/CustomAuthentication.java
  src/main/java/land/leets/Carrot/global/auth/dto/TokenResponse.java
  src/main/java/land/leets/Carrot/global/auth/dto/UserInfoResponse.java
  src/main/java/land/leets/Carrot/global/auth/exception/ErrorMessage.java
  src/main/java/land/leets/Carrot/global/auth/jwt/controller/JwtController.java
  src/main/java/land/leets/Carrot/global/auth/jwt/controller/ResponseMessage.java
  src/main/java/land/leets/Carrot/global/auth/jwt/dto/JwtFilter.java
  src/main/java/land/leets/Carrot/global/auth/jwt/dto/JwtProvider.java
  src/main/java/land/leets/Carrot/global/common/domain/BaseTimeEntity.java
  src/main/java/land/leets/Carrot/global/common/exception/BaseException.java
  src/main/java/land/leets/Carrot/global/common/exception/GlobalExceptionHandler.java
  src/main/java/land/leets/Carrot/global/common/response/ResponseDto.java
  src/main/java/land/leets/Carrot/global/config/SecurityConfig.java
  src/main/java/land/leets/Carrot/global/config/SwaggerConfig.java
Labels: feature

#8 Feature/#4 회원가입 로직 구현
  src/main/java/land/leets/Carrot/domain/user/controller/ResponseMessage.java
  src/main/java/land/leets/Carrot/domain/user/controller/UserController.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/UserSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/UserInfoResponse.java
  src/main/java/land/leets/Carrot/domain/user/entity/User.java
  src/main/java/land/leets/Carrot/domain/user/exception/ErrorMessage.java
  src/main/java/land/leets/Carrot/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/UserNotFoundException.java
  src/main/java/land/leets/Carrot/domain/user/repository/UserRepository.java
  src/main/java/land/leets/Carrot/domain/user/service/UserCreateService.java
  src/main/java/land/leets/Carrot/global/config/SecurityConfig.java
Labels: feature

#14 Feature/#7 회원가입 구직자, 고용자로 분리
  src/main/java/land/leets/Carrot/domain/user/controller/UserController.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/CeoSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/dto/request/EmployeeSignupRequest.java
  src/main/java/land/leets/Carrot/domain/user/entity/User.java
  src/main/java/land/leets/Carrot/domain/user/exception/ErrorMessage.java
  src/main/java/land/leets/Carrot/domain/user/repository/UserRepository.java
  src/main/java/land/leets/Carrot/domain/user/service/UserCreateService.java
Labels: feature

#19 Refactor: global 예외처리 수정
  src/main/java/land/leets/Carrot/domain/user/exception/InvalidPasswordException.java
  src/main/java/land/leets/Carrot/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/UserNotFoundException.java
  src/main/java/land/leets/Carrot/global/common/exception/BaseException.java
Labels: refactor

#20 Refactor: 기존 로직 수정
  src/main/java/land/leets/Carrot/domain/user/controller/ResponseMessage.java
  src/main/java/land/leets/Carrot/domain/user/controller/UserController.java
  src/main/java/land/leets/Carrot/domain/user/dto/response/UserInfoResponse.java
  src/main/java/land/leets/Carrot/domain/user/entity/Ceo.java
  src/main/java/land/leets/Carrot/domain/user/entity/Employee.java
  src/main/java/land/leets/Carrot/domain/user/entity/User.java
  src/main/java/land/leets/Carrot/domain/user/entity/UserType.java
  src/main/java/land/leets/Carrot/domain/user/exception/CeoNameAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/CeoNumberAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/EmailAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/InvalidPasswordException.java
  src/main/java/land/leets/Carrot/domain/user/exception/NicknameAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/TelAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/UserAlreadyExistsException.java
  src/main/java/land/leets/Carrot/domain/user/exception/UserNotFoundException.java
  src/main/java/land/leets/Carrot/domain/user/repository/CeoRepository.java
  src/main/java/land/leets/Carrot/domain/user/repository/EmployeeRepository.java
  src/main/java/land/leets/Carrot/domain/user/repository/UserRepository.java
  src/main/java/land/leets/Carrot/domain/user/service/CeoSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/EmployeeSignupService.java
  src/main/java/land/leets/Carrot/domain/user/service/LoginService.java
  src/main/java/land/leets/Carrot/domain/user/service/UserCreateService.java
  src/main/java/land/leets/Carrot/global/config/SecurityConfig.java
Labels: feature, refactor
